spring.application.name=eureka-server
server.port=8761

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Logging Configuration
logging.file.path=./logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Distributed Tracing Configuration
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
# Disable Zipkin export - we only use tracing for logs in ELK
management.zipkin.tracing.export.enabled=false

